# Start from a Node.js base image with version 16, based on the Alpine Linux distribution
FROM node:16-alpine

# Switch to the "node" user that is created in the base image
USER node

# Create a directory for the application within the node user's home directory
# The -p flag ensures that the directory is created if it doesn't exist
RUN mkdir -p /home/node/app

# Set the working directory for the application
WORKDIR /home/node/app

# Copy the package.json file into the working directory
# The --chown=node:node flag sets the ownership of the copied files to the "node" user and group
COPY --chown=node:node ./package.json ./

# Install the Node.js dependencies defined in package.json
# Since the working directory is set to /home/node/app, npm install will run in this directory
RUN npm install

# Copy the rest of the application files into the working directory
# Again, using --chown=node:node to ensure the node user owns these files
COPY --chown=node:node ./ ./

# Specify the command to run when the container starts
CMD [ "npm", "start"]
